CREATE TABLE IF NOT EXISTS t_user (
    id BIGINT PRIMARY KEY AUTO_INCREMENT,
    username VARCHAR(64) NOT NULL UNIQUE,
    password VARCHAR(128) NOT NULL,
    nickname VARCHAR(64) NOT NULL,
    role_code VARCHAR(32) NOT NULL DEFAULT 'USER',
    permissions VARCHAR(512) NOT NULL DEFAULT '',
    create_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS t_note (
    id BIGINT PRIMARY KEY AUTO_INCREMENT,
    user_id BIGINT NOT NULL,
    title VARCHAR(128) NOT NULL,
    content TEXT NOT NULL,
    create_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    update_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    KEY idx_note_user (user_id)
);

CREATE TABLE IF NOT EXISTS t_announcement (
    id BIGINT PRIMARY KEY AUTO_INCREMENT,
    title VARCHAR(128) NOT NULL,
    content TEXT NOT NULL,
    active TINYINT NOT NULL DEFAULT 1,
    pinned TINYINT NOT NULL DEFAULT 0,
    play_seconds INT NOT NULL DEFAULT 5,
    expire_time TIMESTAMP NULL DEFAULT NULL,
    sort_no INT NOT NULL DEFAULT 100,
    create_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS t_change_log (
    id BIGINT PRIMARY KEY AUTO_INCREMENT,
    version_no VARCHAR(32) NOT NULL,
    module_name VARCHAR(64) NOT NULL,
    change_point VARCHAR(255) NOT NULL,
    change_file VARCHAR(255) NOT NULL,
    git_commit VARCHAR(64) NOT NULL DEFAULT '',
    create_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);
